### ISSUE TITLE
Error when job directory isn't created

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/rapptor#25]
Should check if there's a job directory before trying to include files in it, or not load agenda if theres no jobs?

**Comment by jgallen23** [comment]
Should this happen here or in the Hapi agenda lib?

**Comment by dawnerd** [comment]
hapi-agenda might be the actual problem. Here's the full error:

```
/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/good-mongodb-viewer/node_modules/mongodb/lib/mongodb/mongo_client.js:475
          throw err
                ^
Error: ENOENT, no such file or directory '/Users/troywhiteley/Projects/supersecret/jobs'
    at Object.fs.readdirSync (fs.js:665:18)
    at requireAll (/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/require-all/index.js:12:18)
    at Object.exports.register (/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi-agenda/index.js:31:34)
    at /Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi/lib/plugin.js:235:14
    at iterate (/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at Object.module.exports [as register] (/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi-redirects/lib/index.js:29:3)
    at /Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi/lib/plugin.js:235:14
    at iterate (/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/troywhiteley/Projects/supersecret/node_modules/rapptor/node_modules/hapi/node_modules/items/lib/index.js:27:25)
```
